from PyQt5 import QtCore, QtGui, QtWidgets
from Backend.Modules.Users import *

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(870, 814)
        mainWindow.setWindowTitle("")
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 40, 841, 304))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.textokpo = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.textokpo.setObjectName("textokpo")
        self.gridLayout.addWidget(self.textokpo, 2, 8, 1, 1)
        self.name = QtWidgets.QLabel(self.gridLayoutWidget)
        self.name.setObjectName("name")
        self.gridLayout.addWidget(self.name, 1, 0, 1, 1)
        self.textinn = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.textinn.setObjectName("textinn")
        self.gridLayout.addWidget(self.textinn, 4, 6, 1, 1)
        self.textphone = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.textphone.setObjectName("textphone")
        self.gridLayout.addWidget(self.textphone, 1, 6, 1, 1)
        self.shrt_name = QtWidgets.QLabel(self.gridLayoutWidget)
        self.shrt_name.setObjectName("shrt_name")
        self.gridLayout.addWidget(self.shrt_name, 2, 0, 1, 1)
        self.textinstr_pub_order = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.textinstr_pub_order.setObjectName("textinstr_pub_order")
        self.gridLayout.addWidget(self.textinstr_pub_order, 2, 10, 1, 1)
        self.textjur_addr = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.textjur_addr.setObjectName("textjur_addr")
        self.gridLayout.addWidget(self.textjur_addr, 4, 2, 1, 1)
        self.email = QtWidgets.QLabel(self.gridLayoutWidget)
        self.email.setObjectName("email")
        self.gridLayout.addWidget(self.email, 3, 3, 1, 1)
        self.kpp = QtWidgets.QLabel(self.gridLayoutWidget)
        self.kpp.setObjectName("kpp")
        self.gridLayout.addWidget(self.kpp, 1, 7, 1, 1)
        self.textact_categ = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.textact_categ.setObjectName("textact_categ")
        self.gridLayout.addWidget(self.textact_categ, 4, 10, 1, 1)
        self.textshrt_name = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.textshrt_name.setObjectName("textshrt_name")
        self.gridLayout.addWidget(self.textshrt_name, 2, 2, 1, 1)
        self.o_p_f = QtWidgets.QLabel(self.gridLayoutWidget)
        self.o_p_f.setObjectName("o_p_f")
        self.gridLayout.addWidget(self.o_p_f, 3, 0, 1, 1)
        self.textkpp = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.textkpp.setObjectName("textkpp")
        self.gridLayout.addWidget(self.textkpp, 1, 8, 1, 1)
        self.instr_pub_order = QtWidgets.QLabel(self.gridLayoutWidget)
        self.instr_pub_order.setObjectName("instr_pub_order")
        self.gridLayout.addWidget(self.instr_pub_order, 2, 9, 1, 1)
        self.textin__Reg_stad = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.textin__Reg_stad.setObjectName("textin__Reg_stad")
        self.gridLayout.addWidget(self.textin__Reg_stad, 4, 8, 1, 1)
        self.textName = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.textName.setObjectName("textName")
        self.gridLayout.addWidget(self.textName, 1, 2, 1, 1)
        self.act_categ = QtWidgets.QLabel(self.gridLayoutWidget)
        self.act_categ.setObjectName("act_categ")
        self.gridLayout.addWidget(self.act_categ, 4, 9, 1, 1)
        self.textogrn = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.textogrn.setObjectName("textogrn")
        self.gridLayout.addWidget(self.textogrn, 3, 8, 1, 1)
        self.okpo = QtWidgets.QLabel(self.gridLayoutWidget)
        self.okpo.setObjectName("okpo")
        self.gridLayout.addWidget(self.okpo, 2, 7, 1, 1)
        self.site = QtWidgets.QLabel(self.gridLayoutWidget)
        self.site.setObjectName("site")
        self.gridLayout.addWidget(self.site, 2, 3, 1, 1)
        self.in__Reg_stad = QtWidgets.QLabel(self.gridLayoutWidget)
        self.in__Reg_stad.setObjectName("in__Reg_stad")
        self.gridLayout.addWidget(self.in__Reg_stad, 4, 7, 1, 1)
        self.textemail = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.textemail.setObjectName("textemail")
        self.gridLayout.addWidget(self.textemail, 3, 6, 1, 1)
        self.texto_p_f = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.texto_p_f.setObjectName("texto_p_f")
        self.gridLayout.addWidget(self.texto_p_f, 3, 2, 1, 1)
        self.statd_plan = QtWidgets.QLabel(self.gridLayoutWidget)
        self.statd_plan.setObjectName("statd_plan")
        self.gridLayout.addWidget(self.statd_plan, 2, 11, 1, 1)
        self.phone = QtWidgets.QLabel(self.gridLayoutWidget)
        self.phone.setObjectName("phone")
        self.gridLayout.addWidget(self.phone, 1, 3, 1, 1)
        self.jur_addr = QtWidgets.QLabel(self.gridLayoutWidget)
        self.jur_addr.setObjectName("jur_addr")
        self.gridLayout.addWidget(self.jur_addr, 4, 0, 1, 1)
        self.instr_pub_order_date_until = QtWidgets.QLabel(self.gridLayoutWidget)
        self.instr_pub_order_date_until.setObjectName("instr_pub_order_date_until")
        self.gridLayout.addWidget(self.instr_pub_order_date_until, 3, 9, 1, 1)
        self.texconf_in_expluatation = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.texconf_in_expluatation.setObjectName("texconf_in_expluatation")
        self.gridLayout.addWidget(self.texconf_in_expluatation, 1, 10, 1, 1)
        self.inn = QtWidgets.QLabel(self.gridLayoutWidget)
        self.inn.setObjectName("inn")
        self.gridLayout.addWidget(self.inn, 4, 3, 1, 1)
        self.textsite = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.textsite.setObjectName("textsite")
        self.gridLayout.addWidget(self.textsite, 2, 6, 1, 1)
        self.ogrn = QtWidgets.QLabel(self.gridLayoutWidget)
        self.ogrn.setObjectName("ogrn")
        self.gridLayout.addWidget(self.ogrn, 3, 7, 1, 1)
        self.textinstr_pub_order_date_until = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.textinstr_pub_order_date_until.setObjectName("textinstr_pub_order_date_until")
        self.gridLayout.addWidget(self.textinstr_pub_order_date_until, 3, 10, 1, 1)
        self.conf_in_expluatation = QtWidgets.QLabel(self.gridLayoutWidget)
        self.conf_in_expluatation.setObjectName("conf_in_expluatation")
        self.gridLayout.addWidget(self.conf_in_expluatation, 1, 9, 1, 1)
        self.act_categ_date_until = QtWidgets.QLabel(self.gridLayoutWidget)
        self.act_categ_date_until.setObjectName("act_categ_date_until")
        self.gridLayout.addWidget(self.act_categ_date_until, 1, 11, 1, 1)
        self.textact_categ_date_until = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.textact_categ_date_until.setObjectName("textact_categ_date_until")
        self.gridLayout.addWidget(self.textact_categ_date_until, 1, 12, 1, 1)
        self.textEdit_19 = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.textEdit_19.setObjectName("textEdit_19")
        self.gridLayout.addWidget(self.textEdit_19, 2, 12, 1, 1)


        self.creatStad = QtWidgets.QPushButton(self.centralwidget)
        self.creatStad.setGeometry(QtCore.QRect(320, 350, 211, 41))
        self.creatStad.setObjectName("creatStad")
        self.creatStad.clicked.connect(self.creat_stadium)

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(380, 10, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_42 = QtWidgets.QLabel(self.centralwidget)
        self.label_42.setGeometry(QtCore.QRect(70, 720, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")


        self.creat_club = QtWidgets.QPushButton(self.centralwidget)
        self.creat_club.setGeometry(QtCore.QRect(310, 730, 211, 41))
        self.creat_club.setObjectName("creat_club")
        self.creat_club.clicked.connect(self.start_club)




        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(20, 410, 841, 304))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.textokpo_2 = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.textokpo_2.setObjectName("textokpo_2")
        self.gridLayout_2.addWidget(self.textokpo_2, 2, 8, 1, 1)
        self.name_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.name_2.setObjectName("name_2")
        self.gridLayout_2.addWidget(self.name_2, 1, 0, 1, 1)
        self.textinn_2 = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.textinn_2.setObjectName("textinn_2")
        self.gridLayout_2.addWidget(self.textinn_2, 4, 6, 1, 1)
        self.textphone_2 = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.textphone_2.setObjectName("textphone_2")
        self.gridLayout_2.addWidget(self.textphone_2, 1, 6, 1, 1)
        self.shrt_name_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.shrt_name_2.setObjectName("shrt_name_2")
        self.gridLayout_2.addWidget(self.shrt_name_2, 2, 0, 1, 1)
        self.textinstr_pub_order_2 = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.textinstr_pub_order_2.setObjectName("textinstr_pub_order_2")
        self.gridLayout_2.addWidget(self.textinstr_pub_order_2, 2, 10, 1, 1)
        self.textjur_addr_2 = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.textjur_addr_2.setObjectName("textjur_addr_2")
        self.gridLayout_2.addWidget(self.textjur_addr_2, 4, 2, 1, 1)
        self.email_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.email_2.setObjectName("email_2")
        self.gridLayout_2.addWidget(self.email_2, 3, 3, 1, 1)
        self.kpp_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.kpp_2.setObjectName("kpp_2")
        self.gridLayout_2.addWidget(self.kpp_2, 1, 7, 1, 1)
        self.textact_categ_2 = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.textact_categ_2.setObjectName("textact_categ_2")
        self.gridLayout_2.addWidget(self.textact_categ_2, 4, 10, 1, 1)
        self.textshrt_name_2 = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.textshrt_name_2.setObjectName("textshrt_name_2")
        self.gridLayout_2.addWidget(self.textshrt_name_2, 2, 2, 1, 1)
        self.o_p_f_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.o_p_f_2.setObjectName("o_p_f_2")
        self.gridLayout_2.addWidget(self.o_p_f_2, 3, 0, 1, 1)
        self.textkpp_2 = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.textkpp_2.setObjectName("textkpp_2")
        self.gridLayout_2.addWidget(self.textkpp_2, 1, 8, 1, 1)
        self.instr_pub_order_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.instr_pub_order_2.setObjectName("instr_pub_order_2")
        self.gridLayout_2.addWidget(self.instr_pub_order_2, 2, 9, 1, 1)
        self.textin__Reg_stad_2 = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.textin__Reg_stad_2.setObjectName("textin__Reg_stad_2")
        self.gridLayout_2.addWidget(self.textin__Reg_stad_2, 4, 8, 1, 1)
        self.textName_2 = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.textName_2.setObjectName("textName_2")
        self.gridLayout_2.addWidget(self.textName_2, 1, 2, 1, 1)
        self.act_categ_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.act_categ_2.setObjectName("act_categ_2")
        self.gridLayout_2.addWidget(self.act_categ_2, 4, 9, 1, 1)
        self.textogrn_2 = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.textogrn_2.setObjectName("textogrn_2")
        self.gridLayout_2.addWidget(self.textogrn_2, 3, 8, 1, 1)
        self.okpo_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.okpo_2.setObjectName("okpo_2")
        self.gridLayout_2.addWidget(self.okpo_2, 2, 7, 1, 1)
        self.site_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.site_2.setObjectName("site_2")
        self.gridLayout_2.addWidget(self.site_2, 2, 3, 1, 1)
        self.bank_name = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.bank_name.setObjectName("bank_name")
        self.gridLayout_2.addWidget(self.in__Reg_stad_2, 4, 7, 1, 1)
        self.textemail_2 = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.textemail_2.setObjectName("textemail_2")
        self.gridLayout_2.addWidget(self.textemail_2, 3, 6, 1, 1)
        self.texto_p_f_2 = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.texto_p_f_2.setObjectName("texto_p_f_2")
        self.gridLayout_2.addWidget(self.texto_p_f_2, 3, 2, 1, 1)
        self.statd_plan_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.statd_plan_2.setObjectName("statd_plan_2")
        self.gridLayout_2.addWidget(self.statd_plan_2, 2, 11, 1, 1)
        self.phone_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.phone_2.setObjectName("phone_2")
        self.gridLayout_2.addWidget(self.phone_2, 1, 3, 1, 1)
        self.jur_addr_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.jur_addr_2.setObjectName("jur_addr_2")
        self.gridLayout_2.addWidget(self.jur_addr_2, 4, 0, 1, 1)
        self.instr_pub_order_date_until_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.instr_pub_order_date_until_2.setObjectName("instr_pub_order_date_until_2")
        self.gridLayout_2.addWidget(self.instr_pub_order_date_until_2, 3, 9, 1, 1)
        self.texconf_in_expluatation_2 = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.texconf_in_expluatation_2.setObjectName("texconf_in_expluatation_2")
        self.gridLayout_2.addWidget(self.texconf_in_expluatation_2, 1, 10, 1, 1)
        self.inn_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.inn_2.setObjectName("inn_2")
        self.gridLayout_2.addWidget(self.inn_2, 4, 3, 1, 1)
        self.textsite_2 = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.textsite_2.setObjectName("textsite_2")
        self.gridLayout_2.addWidget(self.textsite_2, 2, 6, 1, 1)
        self.ogrn_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.ogrn_2.setObjectName("ogrn_2")
        self.gridLayout_2.addWidget(self.ogrn_2, 3, 7, 1, 1)
        self.textinstr_pub_order_date_until_2 = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.textinstr_pub_order_date_until_2.setObjectName("textinstr_pub_order_date_until_2")
        self.gridLayout_2.addWidget(self.textinstr_pub_order_date_until_2, 3, 10, 1, 1)
        self.conf_in_expluatation_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.conf_in_expluatation_2.setObjectName("conf_in_expluatation_2")
        self.gridLayout_2.addWidget(self.conf_in_expluatation_2, 1, 9, 1, 1)
        self.act_categ_date_until_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.act_categ_date_until_2.setObjectName("act_categ_date_until_2")
        self.gridLayout_2.addWidget(self.act_categ_date_until_2, 1, 11, 1, 1)
        self.textact_categ_date_until_2 = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.textact_categ_date_until_2.setObjectName("textact_categ_date_until_2")
        self.gridLayout_2.addWidget(self.textact_categ_date_until_2, 1, 12, 1, 1)
        self.textEdit_20 = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.textEdit_20.setObjectName("textEdit_20")
        self.gridLayout_2.addWidget(self.textEdit_20, 2, 12, 1, 1)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 870, 21))
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.name.setText(_translate("mainWindow", "name"))
        self.shrt_name.setText(_translate("mainWindow", "shrt_name"))
        self.email.setText(_translate("mainWindow", "email"))
        self.kpp.setText(_translate("mainWindow", "kpp"))
        self.o_p_f.setText(_translate("mainWindow", "o_p_f"))
        self.instr_pub_order.setText(_translate("mainWindow", "instr_pub_order"))
        self.act_categ.setText(_translate("mainWindow", "act_categ"))
        self.okpo.setText(_translate("mainWindow", "okpo"))
        self.site.setText(_translate("mainWindow", "site"))
        self.in__Reg_stad.setText(_translate("mainWindow", "in__Reg_stad"))
        self.statd_plan.setText(_translate("mainWindow", "statd_plan"))
        self.phone.setText(_translate("mainWindow", "phone"))
        self.jur_addr.setText(_translate("mainWindow", "jur_addr"))
        self.instr_pub_order_date_until.setText(_translate("mainWindow", "instr_pub_order_date_until"))
        self.inn.setText(_translate("mainWindow", "inn"))
        self.ogrn.setText(_translate("mainWindow", "ogrn"))
        self.conf_in_expluatation.setText(_translate("mainWindow", "conf_in_expluatation"))
        self.act_categ_date_until.setText(_translate("mainWindow", "act_categ_date_until"))
        self.creatStad.setText(_translate("mainWindow", "Создать Стадион"))
        self.label.setText(_translate("mainWindow", "Стадион"))
        self.label_42.setText(_translate("mainWindow", "Клуб"))
        self.creat_club.setText(_translate("mainWindow", "Создать Клуб"))
        self.name_2.setText(_translate("mainWindow", "name"))
        self.shrt_name_2.setText(_translate("mainWindow", "shrt_name"))
        self.email_2.setText(_translate("mainWindow", "email"))
        self.kpp_2.setText(_translate("mainWindow", "kpp"))
        self.o_p_f_2.setText(_translate("mainWindow", "o_p_f"))
        self.instr_pub_order_2.setText(_translate("mainWindow", "instr_pub_order"))
        self.act_categ_2.setText(_translate("mainWindow", "act_categ"))
        self.okpo_2.setText(_translate("mainWindow", "okpo"))
        self.site_2.setText(_translate("mainWindow", "site"))
        self.in__Reg_stad_2.setText(_translate("mainWindow", "in__Reg_stad"))
        self.statd_plan_2.setText(_translate("mainWindow", "statd_plan"))
        self.phone_2.setText(_translate("mainWindow", "phone"))
        self.jur_addr_2.setText(_translate("mainWindow", "jur_addr"))
        self.instr_pub_order_date_until_2.setText(_translate("mainWindow", "instr_pub_order_date_until"))
        self.inn_2.setText(_translate("mainWindow", "inn"))
        self.ogrn_2.setText(_translate("mainWindow", "ogrn"))
        self.conf_in_expluatation_2.setText(_translate("mainWindow", "conf_in_expluatation"))
        self.act_categ_date_until_2.setText(_translate("mainWindow", "act_categ_date_until"))


    def creat_stadium(self):
        name=self.textName.toPlainText()
        shrt_name=self.textshrt_name.toPlainText()
        o_p_f=self.texto_p_f.toPlainText()
        jur_addr=self.textjur_addr.toPlainText()
        phone=self.textphone.toPlainText()
        site=self.textsite.toPlainText()
        email=self.textemail.toPlainText()
        inn=self.textinn.toPlainText()
        kpp=self.textkpp.toPlainText()
        okpo=self.textokpo.toPlainText()
        ogrn=self.textogrn.toPlainText()
        in__Reg_stad=self.textin__Reg_stad.toPlainText()
        conf_in_expluatation=self.texconf_in_expluatation.toPlainText()
        instr_pub_order=self.textinstr_pub_order.toPlainText()
        instr_pub_order_date_until=self.textinstr_pub_order_date_until.toPlainText()
        act_categ=self.textact_categ.toPlainText()
        act_categ_date_until=self.textact_categ_date_until.toPlainText()
        statd_plan=self.textEdit_19.toPlainText()
        print(name,shrt_name,o_p_f,jur_addr,phone,site,email,inn,kpp,okpo,ogrn,in__Reg_stad,
              conf_in_expluatation,instr_pub_order,instr_pub_order_date_until,act_categ,
              act_categ_date_until,statd_plan)
        stad=Stadium(name,shrt_name,o_p_f,jur_addr,phone,site,email,inn,kpp,okpo,ogrn,in__Reg_stad,
                      conf_in_expluatation,instr_pub_order,instr_pub_order_date_until,act_categ,
                      act_categ_date_until,statd_plan)
        stad.add_to_db()
        print('Стадион создан')

    def creat_clubs(self):
        name_2 = self.self.name_2.toPlainText()
        shrt_name_2 = self.textshrt_name_2.toPlainText()
        o_p_f_2 = self.texto_p_f_2.toPlainText()
        jur_addr_2 = self.textjur_addr_2.toPlainText()
        phone_2 = self.textphone_2.toPlainText()
        site_2 = self.textsite_2.toPlainText()
        email_2 = self.textemail_2.toPlainText()
        inn_2 = self.textinn_2.toPlainText()
        kpp_2 = self.textkpp_2.toPlainText()
        okpo_2 = self.textokpo_2.toPlainText()
        ogrn_2 = self.textogrn_2.toPlainText()
        bank_name = self.textbank_name.toPlainText()
        cor_ac = self.texcor_ac.toPlainText()
        check_ac = self.textcheck_ac.toPlainText()
        bik = self.textbik.toPlainText()
        ustav = self.textustav.toPlainText()
        reg_in_min_just = self.textreg_in_min_just.toPlainText()
        reg_in_tax = self.textreg_in_tax.toPlainText()
        creat_club= self.textcreat_club.toPlainText()
        creat_rucovod= self.textcreat_club.toPlainText()
        ofice= self.textcreat_club.toPlainText()
        print(name_2, shrt_name_2, o_p_f_2, jur_addr_2, phone_2, site_2, email_2, inn_2, kpp_2,
                           okpo_2, ogrn_2, bank_name, cor_ac, check_ac, bik, ustav,reg_in_min_just, reg_in_tax,
                           creat_club,creat_rucovod,ofice)
        club = Club(name_2, shrt_name_2, o_p_f_2, jur_addr_2, phone_2, site_2, email_2, inn_2, kpp_2,
                           okpo_2, ogrn_2, bank_name, cor_ac, check_ac, bik, ustav,reg_in_min_just, reg_in_tax,
                           creat_club,creat_rucovod,ofice)
        club.add_to_db()
        print('Клуб создан')

    def start_club():
        app = QtWidgets.QApplication([])
        application1 = WindowCreatClub()
        application1.show()
        sys.exit(app.exec())

class WindowCreatClub(object):
    def setupUi(self, mainWindow):
            mainWindow.setObjectName("New club")
            mainWindow.resize(400, 400)
            mainWindow.setWindowTitle("Новый клуб")
            self.retranslateUi(MainWindow)
            QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("New club", "New club"))
