import sys
import os
print(os.getcwd())
# from ..Backend.Modules.Users import *
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QWidget, QPushButton,QCommandLinkButton

class WindowClub(QWidget):
    def __init__(self):
        super(WindowClub, self).__init__()
        self.setObjectName("Creat_Club")
        self.resize(883, 846)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        font.setItalic(True)
        self.setFont(font)
        self.horizontalLayoutWidget = QWidget(self)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 841, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.name_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.name_2.setContentsMargins(11, 0, 0, 0)
        self.name_2.setSpacing(8)
        self.name_2.setObjectName("name_2")
        self.name = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setItalic(True)
        self.name.setFont(font)
        self.name.setObjectName("name")
        self.name_2.addWidget(self.name)
        self.textname = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        # self.textname.setFocusPolicy(QtCore.Qt.NoFocus)
        self.textname.setObjectName("textname")
        self.name_2.addWidget(self.textname)
        self.horizontalLayoutWidget_2 = QWidget(self)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 70, 841, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.shrt_name_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.shrt_name_2.setContentsMargins(11, 0, 1, 0)
        self.shrt_name_2.setSpacing(8)
        self.shrt_name_2.setObjectName("shrt_name_2")
        self.shrt_name = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.shrt_name.setObjectName("shrt_name")
        self.shrt_name_2.addWidget(self.shrt_name)
        self.textshrt_name = QtWidgets.QTextEdit(self.horizontalLayoutWidget_2)
        # self.textshrt_name.setFocusPolicy(QtCore.Qt.NoFocus)
        self.textshrt_name.setObjectName("textshrt_name")
        self.shrt_name_2.addWidget(self.textshrt_name)
        self.horizontalLayoutWidget_3 = QWidget(self)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 120, 841, 31))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.o_p_f_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.o_p_f_2.setContentsMargins(11, 0, 1, 0)
        self.o_p_f_2.setSpacing(8)
        self.o_p_f_2.setObjectName("o_p_f_2")
        self.o_p_f = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.o_p_f.setWordWrap(False)
        self.o_p_f.setObjectName("o_p_f")
        self.o_p_f_2.addWidget(self.o_p_f)
        self.texto_p_f = QtWidgets.QTextEdit(self.horizontalLayoutWidget_3)
        self.texto_p_f.setObjectName("texto_p_f")
        self.o_p_f_2.addWidget(self.texto_p_f)
        self.horizontalLayoutWidget_4 = QWidget(self)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 170, 841, 31))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.jur_addr_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.jur_addr_2.setContentsMargins(11, 0, 1, 0)
        self.jur_addr_2.setSpacing(8)
        self.jur_addr_2.setObjectName("jur_addr_2")
        self.jur_addr = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.jur_addr.setObjectName("jur_addr")
        self.jur_addr_2.addWidget(self.jur_addr)
        self.textjur_addr = QtWidgets.QTextEdit(self.horizontalLayoutWidget_4)
        self.textjur_addr.setObjectName("textjur_addr")
        self.jur_addr_2.addWidget(self.textjur_addr)
        self.horizontalLayoutWidget_6 = QWidget(self)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(10, 270, 841, 31))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.site_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.site_2.setContentsMargins(11, 0, 1, 0)
        self.site_2.setSpacing(8)
        self.site_2.setObjectName("site_2")
        self.site = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.site.setObjectName("site")
        self.site_2.addWidget(self.site)
        self.textsite = QtWidgets.QTextEdit(self.horizontalLayoutWidget_6)
        self.textsite.setObjectName("textsite")
        self.site_2.addWidget(self.textsite)
        self.horizontalLayoutWidget_5 = QWidget(self)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 220, 301, 31))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.phone_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.phone_2.setContentsMargins(11, 0, 1, 0)
        self.phone_2.setSpacing(8)
        self.phone_2.setObjectName("phone_2")
        self.phone = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.phone.setObjectName("phone")
        self.phone_2.addWidget(self.phone)
        self.textphone = QtWidgets.QTextEdit(self.horizontalLayoutWidget_5)
        self.textphone.setObjectName("textphone")
        self.phone_2.addWidget(self.textphone)
        self.horizontalLayoutWidget_7 = QWidget(self)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(10, 320, 841, 31))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.email_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.email_2.setContentsMargins(11, 0, 1, 0)
        self.email_2.setSpacing(8)
        self.email_2.setObjectName("email_2")
        self.email = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        self.email.setObjectName("email")
        self.email_2.addWidget(self.email)
        self.textemail = QtWidgets.QTextEdit(self.horizontalLayoutWidget_7)
        self.textemail.setObjectName("textemail")
        self.email_2.addWidget(self.textemail)
        self.horizontalLayoutWidget_9 = QWidget(self)
        self.horizontalLayoutWidget_9.setGeometry(QtCore.QRect(320, 370, 301, 31))
        self.horizontalLayoutWidget_9.setObjectName("horizontalLayoutWidget_9")
        self.kpp_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_9)
        self.kpp_2.setContentsMargins(11, 0, 1, 0)
        self.kpp_2.setSpacing(8)
        self.kpp_2.setObjectName("kpp_2")
        self.kpp = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        self.kpp.setObjectName("kpp")
        self.kpp_2.addWidget(self.kpp)
        self.textkpp = QtWidgets.QTextEdit(self.horizontalLayoutWidget_9)
        self.textkpp.setObjectName("textkpp")
        self.kpp_2.addWidget(self.textkpp)
        self.horizontalLayoutWidget_10 = QWidget(self)
        self.horizontalLayoutWidget_10.setGeometry(QtCore.QRect(10, 420, 301, 31))
        self.horizontalLayoutWidget_10.setObjectName("horizontalLayoutWidget_10")
        self.okpo_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_10)
        self.okpo_2.setContentsMargins(11, 0, 1, 0)
        self.okpo_2.setSpacing(8)
        self.okpo_2.setObjectName("okpo_2")
        self.okpo = QtWidgets.QLabel(self.horizontalLayoutWidget_10)
        self.okpo.setObjectName("okpo")
        self.okpo_2.addWidget(self.okpo)
        self.textokpo = QtWidgets.QTextEdit(self.horizontalLayoutWidget_10)
        self.textokpo.setObjectName("textokpo")
        self.okpo_2.addWidget(self.textokpo)
        self.horizontalLayoutWidget_8 = QWidget(self)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(10, 370, 301, 31))
        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_8")
        self.inn_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.inn_2.setContentsMargins(11, 0, 1, 0)
        self.inn_2.setSpacing(8)
        self.inn_2.setObjectName("inn_2")
        self.inn = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        self.inn.setObjectName("inn")
        self.inn_2.addWidget(self.inn)
        self.textinn = QtWidgets.QTextEdit(self.horizontalLayoutWidget_8)
        self.textinn.setObjectName("textinn")
        self.inn_2.addWidget(self.textinn)
        self.horizontalLayoutWidget_11 = QWidget(self)
        self.horizontalLayoutWidget_11.setGeometry(QtCore.QRect(320, 420, 301, 31))
        self.horizontalLayoutWidget_11.setObjectName("horizontalLayoutWidget_11")
        self.ogrn_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_11)
        self.ogrn_2.setContentsMargins(11, 0, 1, 0)
        self.ogrn_2.setSpacing(8)
        self.ogrn_2.setObjectName("ogrn_2")
        self.ogrn = QtWidgets.QLabel(self.horizontalLayoutWidget_11)
        self.ogrn.setObjectName("ogrn")
        self.ogrn_2.addWidget(self.ogrn)
        self.textogrn = QtWidgets.QTextEdit(self.horizontalLayoutWidget_11)
        self.textogrn.setObjectName("textogrn")
        self.ogrn_2.addWidget(self.textogrn)
        self.horizontalLayoutWidget_12 = QWidget(self)
        self.horizontalLayoutWidget_12.setGeometry(QtCore.QRect(10, 470, 841, 31))
        self.horizontalLayoutWidget_12.setObjectName("horizontalLayoutWidget_12")
        self.bank_name_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_12)
        self.bank_name_2.setContentsMargins(11, 0, 1, 0)
        self.bank_name_2.setSpacing(8)
        self.bank_name_2.setObjectName("bank_name_2")
        self.bank_name = QtWidgets.QLabel(self.horizontalLayoutWidget_12)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        font.setItalic(True)
        self.bank_name.setFont(font)
        self.bank_name.setAutoFillBackground(False)
        self.bank_name.setStyleSheet("")
        self.bank_name.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.bank_name.setFrameShadow(QtWidgets.QFrame.Plain)
        self.bank_name.setLineWidth(1)
        self.bank_name.setWordWrap(False)
        self.bank_name.setObjectName("bank_name")
        self.bank_name_2.addWidget(self.bank_name)
        self.textbank_name = QtWidgets.QTextEdit(self.horizontalLayoutWidget_12)
        # self.textbank_name.setFocusPolicy(QtCore.Qt.NoFocus)
        self.textbank_name.setObjectName("textbank_name")
        self.bank_name_2.addWidget(self.textbank_name)
        self.horizontalLayoutWidget_18 = QWidget(self)
        self.horizontalLayoutWidget_18.setGeometry(QtCore.QRect(480, 670, 391, 31))
        self.horizontalLayoutWidget_18.setObjectName("horizontalLayoutWidget_18")
        self.reg_in_tax_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_18)
        self.reg_in_tax_2.setContentsMargins(11, 0, 1, 0)
        self.reg_in_tax_2.setSpacing(8)
        self.reg_in_tax_2.setObjectName("reg_in_tax_2")
        self.reg_in_tax = QtWidgets.QLabel(self.horizontalLayoutWidget_18)
        self.reg_in_tax.setStyleSheet("background-color: rgb(255, 0, 255);")
        self.reg_in_tax.setObjectName("reg_in_tax")
        self.reg_in_tax_2.addWidget(self.reg_in_tax)
        self.textreg_in_tax = QtWidgets.QTextEdit(self.horizontalLayoutWidget_18)
        self.textreg_in_tax.setObjectName("textreg_in_tax")
        self.reg_in_tax_2.addWidget(self.textreg_in_tax)
        self.horizontalLayoutWidget_17 = QWidget(self)
        self.horizontalLayoutWidget_17.setGeometry(QtCore.QRect(10, 670, 461, 31))
        self.horizontalLayoutWidget_17.setObjectName("horizontalLayoutWidget_17")
        self.reg_in_min_just_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_17)
        self.reg_in_min_just_2.setContentsMargins(11, 0, 1, 0)
        self.reg_in_min_just_2.setSpacing(8)
        self.reg_in_min_just_2.setObjectName("reg_in_min_just_2")
        self.reg_in_min_just = QtWidgets.QLabel(self.horizontalLayoutWidget_17)
        self.reg_in_min_just.setStyleSheet("\n"
                                           "background-color: rgb(255, 0, 255);")
        self.reg_in_min_just.setObjectName("reg_in_min_just")
        self.reg_in_min_just_2.addWidget(self.reg_in_min_just)
        self.textreg_in_min_just = QtWidgets.QTextEdit(self.horizontalLayoutWidget_17)
        self.textreg_in_min_just.setObjectName("textreg_in_min_just")
        self.reg_in_min_just_2.addWidget(self.textreg_in_min_just)
        self.horizontalLayoutWidget_13 = QWidget(self)
        self.horizontalLayoutWidget_13.setGeometry(QtCore.QRect(10, 520, 841, 31))
        self.horizontalLayoutWidget_13.setObjectName("horizontalLayoutWidget_13")
        self.cor_ac_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_13)
        self.cor_ac_2.setContentsMargins(11, 0, 1, 0)
        self.cor_ac_2.setSpacing(8)
        self.cor_ac_2.setObjectName("cor_ac_2")
        self.cor_ac = QtWidgets.QLabel(self.horizontalLayoutWidget_13)
        self.cor_ac.setStyleSheet("font: italic 16pt \"Comic Sans MS\";")
        self.cor_ac.setObjectName("cor_ac")
        self.cor_ac_2.addWidget(self.cor_ac)
        self.textcor_ac = QtWidgets.QTextEdit(self.horizontalLayoutWidget_13)
        self.textcor_ac.setObjectName("textcor_ac")
        self.cor_ac_2.addWidget(self.textcor_ac)
        self.horizontalLayoutWidget_15 = QWidget(self)
        self.horizontalLayoutWidget_15.setGeometry(QtCore.QRect(10, 620, 291, 31))
        self.horizontalLayoutWidget_15.setObjectName("horizontalLayoutWidget_15")
        self.bik_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_15)
        self.bik_2.setContentsMargins(11, 0, 1, 0)
        self.bik_2.setSpacing(8)
        self.bik_2.setObjectName("bik_2")
        self.bik = QtWidgets.QLabel(self.horizontalLayoutWidget_15)
        self.bik.setObjectName("bik")
        self.bik_2.addWidget(self.bik)
        self.textbik = QtWidgets.QTextEdit(self.horizontalLayoutWidget_15)
        self.textbik.setObjectName("textbik")
        self.bik_2.addWidget(self.textbik)
        self.horizontalLayoutWidget_14 = QWidget(self)
        self.horizontalLayoutWidget_14.setGeometry(QtCore.QRect(10, 570, 841, 31))
        self.horizontalLayoutWidget_14.setObjectName("horizontalLayoutWidget_14")
        self.check_ac_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_14)
        self.check_ac_2.setContentsMargins(11, 0, 1, 0)
        self.check_ac_2.setSpacing(8)
        self.check_ac_2.setObjectName("check_ac_2")
        self.check_ac = QtWidgets.QLabel(self.horizontalLayoutWidget_14)
        self.check_ac.setStyleSheet("font: italic 16pt \"Comic Sans MS\";")
        self.check_ac.setObjectName("check_ac")
        self.check_ac_2.addWidget(self.check_ac)
        self.textcheck_ac = QtWidgets.QTextEdit(self.horizontalLayoutWidget_14)
        self.textcheck_ac.setObjectName("textcheck_ac")
        self.check_ac_2.addWidget(self.textcheck_ac)
        self.horizontalLayoutWidget_16 = QWidget(self)
        self.horizontalLayoutWidget_16.setGeometry(QtCore.QRect(310, 620, 541, 31))
        self.horizontalLayoutWidget_16.setObjectName("horizontalLayoutWidget_16")
        self.ustav_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_16)
        self.ustav_2.setContentsMargins(11, 0, 1, 0)
        self.ustav_2.setSpacing(8)
        self.ustav_2.setObjectName("ustav_2")
        self.ustav = QtWidgets.QLabel(self.horizontalLayoutWidget_16)
        self.ustav.setStyleSheet("background-color: rgb(255, 0, 255);")
        self.ustav.setObjectName("ustav")
        self.ustav_2.addWidget(self.ustav)
        self.textustav = QtWidgets.QTextEdit(self.horizontalLayoutWidget_16)
        self.textustav.setObjectName("textustav")
        self.ustav_2.addWidget(self.textustav)
        self.horizontalLayoutWidget_19 = QWidget(self)
        self.horizontalLayoutWidget_19.setGeometry(QtCore.QRect(10, 710, 461, 31))
        self.horizontalLayoutWidget_19.setObjectName("horizontalLayoutWidget_19")
        self.creat_club_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_19)
        self.creat_club_2.setContentsMargins(11, 0, 1, 0)
        self.creat_club_2.setSpacing(8)
        self.creat_club_2.setObjectName("creat_club_2")
        self.creat_club = QtWidgets.QLabel(self.horizontalLayoutWidget_19)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        font.setItalic(True)
        self.creat_club.setFont(font)
        self.creat_club.setStyleSheet("\n"
                                      "background-color: rgb(255, 0, 255);")
        self.creat_club.setObjectName("creat_club")
        self.creat_club_2.addWidget(self.creat_club)
        self.textcreat_club = QtWidgets.QTextEdit(self.horizontalLayoutWidget_19)
        self.textcreat_club.setObjectName("textcreat_club")
        self.creat_club_2.addWidget(self.textcreat_club)
        self.horizontalLayoutWidget_20 = QWidget(self)
        self.horizontalLayoutWidget_20.setGeometry(QtCore.QRect(10, 760, 461, 31))
        self.horizontalLayoutWidget_20.setObjectName("horizontalLayoutWidget_20")
        self.reg_in_min_just_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_20)
        self.reg_in_min_just_5.setContentsMargins(11, 0, 1, 0)
        self.reg_in_min_just_5.setSpacing(8)
        self.reg_in_min_just_5.setObjectName("reg_in_min_just_5")
        self.reg_in_min_just_6 = QtWidgets.QLabel(self.horizontalLayoutWidget_20)
        self.reg_in_min_just_6.setStyleSheet("\n"
                                             "background-color: rgb(255, 0, 255);")
        self.reg_in_min_just_6.setObjectName("reg_in_min_just_6")
        self.reg_in_min_just_5.addWidget(self.reg_in_min_just_6)
        self.textreg_in_min_just_3 = QtWidgets.QTextEdit(self.horizontalLayoutWidget_20)
        self.textreg_in_min_just_3.setObjectName("textreg_in_min_just_3")
        self.reg_in_min_just_5.addWidget(self.textreg_in_min_just_3)
        self.horizontalLayoutWidget_22 = QWidget(self)
        self.horizontalLayoutWidget_22.setGeometry(QtCore.QRect(10, 810, 461, 31))
        self.horizontalLayoutWidget_22.setObjectName("horizontalLayoutWidget_22")
        self.reg_in_min_just_9 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_22)
        self.reg_in_min_just_9.setContentsMargins(11, 0, 1, 0)
        self.reg_in_min_just_9.setSpacing(8)
        self.reg_in_min_just_9.setObjectName("reg_in_min_just_9")
        self.reg_in_min_just_10 = QtWidgets.QLabel(self.horizontalLayoutWidget_22)
        self.reg_in_min_just_10.setStyleSheet("\n"
                                              "background-color: rgb(255, 0, 255);")
        self.reg_in_min_just_10.setObjectName("reg_in_min_just_10")
        self.reg_in_min_just_9.addWidget(self.reg_in_min_just_10)
        self.textreg_in_min_just_5 = QtWidgets.QTextEdit(self.horizontalLayoutWidget_22)
        self.textreg_in_min_just_5.setObjectName("textreg_in_min_just_5")
        self.reg_in_min_just_9.addWidget(self.textreg_in_min_just_5)
        self.creat_club_3 = QCommandLinkButton(self)
        self.creat_club_3.setGeometry(QtCore.QRect(610, 720, 241, 71))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        font.setItalic(True)
        self.creat_club_3.setFont(font)
        self.creat_club_3.setStyleSheet("\n"
                                        "background-color: rgb(85, 255, 127);")
        self.creat_club_3.setObjectName("creat_club_3")

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self, Creat_Club):
        _translate = QtCore.QCoreApplication.translate
        Creat_Club.setWindowTitle(_translate("Creat_Club", "Form"))
        self.name.setText(_translate("Creat_Club", "Название Клуба"))
        self.shrt_name.setText(_translate("Creat_Club", "Сокращенное название"))
        self.o_p_f.setText(_translate("Creat_Club", "Организацонное-правовая форма"))
        self.jur_addr.setText(_translate("Creat_Club", "Адрес"))
        self.site.setText(_translate("Creat_Club", "Сайт"))
        self.phone.setText(_translate("Creat_Club", "Телефон"))
        self.email.setText(_translate("Creat_Club", "email"))
        self.kpp.setText(_translate("Creat_Club", "КПП"))
        self.okpo.setText(_translate("Creat_Club", "ОКПО"))
        self.inn.setText(_translate("Creat_Club", "ИНН"))
        self.ogrn.setText(_translate("Creat_Club", "ОГРН"))
        self.bank_name.setText(_translate("Creat_Club", "bank_name"))
        self.reg_in_tax.setText(_translate("Creat_Club", "регистрация в налоговой"))
        self.reg_in_min_just.setText(_translate("Creat_Club", "регистрация в минюсте"))
        self.cor_ac.setText(_translate("Creat_Club", "cor_ac"))
        self.bik.setText(_translate("Creat_Club", "bik"))
        self.check_ac.setText(_translate("Creat_Club", "check_ac"))
        self.ustav.setText(_translate("Creat_Club", "Устав"))
        self.creat_club.setText(_translate("Creat_Club", "Протокол о создании клуба"))
        self.reg_in_min_just_6.setText(_translate("Creat_Club", "протокол о назначении руководителя"))
        self.reg_in_min_just_10.setText(_translate("Creat_Club", "офис"))
        self.creat_club_3.setText(_translate("Creat_Club", "Создать"))

class WindowStadium(QWidget):
    def __init__(self):
        super(WindowStadium, self).__init__()
        self.setObjectName("Creat_Stadium")
        self.resize(849, 905)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        font.setItalic(True)
        self.setFont(font)
        self.horizontalLayoutWidget = QWidget(self)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 10, 841, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.name_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.name_2.setContentsMargins(11, 0, 0, 0)
        self.name_2.setSpacing(8)
        self.name_2.setObjectName("name_2")
        self.name = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setItalic(True)
        self.name.setFont(font)
        self.name.setObjectName("name")
        self.name_2.addWidget(self.name)
        self.textname = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        # self.textname.setFocusPolicy(QtCore.Qt.NoFocus)
        self.textname.setObjectName("textname")
        self.name_2.addWidget(self.textname)
        self.horizontalLayoutWidget_2 = QWidget(self)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 50, 841, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.shrt_name_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.shrt_name_2.setContentsMargins(11, 0, 1, 0)
        self.shrt_name_2.setSpacing(8)
        self.shrt_name_2.setObjectName("shrt_name_2")
        self.shrt_name = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.shrt_name.setObjectName("shrt_name")
        self.shrt_name_2.addWidget(self.shrt_name)
        self.textshrt_name = QtWidgets.QTextEdit(self.horizontalLayoutWidget_2)
        # self.textshrt_name.setFocusPolicy(QtCore.Qt.NoFocus)
        self.textshrt_name.setObjectName("textshrt_name")
        self.shrt_name_2.addWidget(self.textshrt_name)
        self.horizontalLayoutWidget_3 = QWidget(self)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(0, 100, 841, 31))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.o_p_f_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.o_p_f_2.setContentsMargins(11, 0, 1, 0)
        self.o_p_f_2.setSpacing(8)
        self.o_p_f_2.setObjectName("o_p_f_2")
        self.o_p_f = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.o_p_f.setWordWrap(False)
        self.o_p_f.setObjectName("o_p_f")
        self.o_p_f_2.addWidget(self.o_p_f)
        self.texto_p_f = QtWidgets.QTextEdit(self.horizontalLayoutWidget_3)
        self.texto_p_f.setObjectName("texto_p_f")
        self.o_p_f_2.addWidget(self.texto_p_f)
        self.horizontalLayoutWidget_4 = QWidget(self)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(0, 150, 841, 31))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.jur_addr_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.jur_addr_2.setContentsMargins(11, 0, 1, 0)
        self.jur_addr_2.setSpacing(8)
        self.jur_addr_2.setObjectName("jur_addr_2")
        self.jur_addr = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.jur_addr.setObjectName("jur_addr")
        self.jur_addr_2.addWidget(self.jur_addr)
        self.textjur_addr = QtWidgets.QTextEdit(self.horizontalLayoutWidget_4)
        self.textjur_addr.setObjectName("textjur_addr")
        self.jur_addr_2.addWidget(self.textjur_addr)
        self.horizontalLayoutWidget_5 = QWidget(self)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(0, 200, 841, 31))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.phone_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.phone_2.setContentsMargins(11, 0, 1, 0)
        self.phone_2.setSpacing(8)
        self.phone_2.setObjectName("phone_2")
        self.phone = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.phone.setObjectName("phone")
        self.phone_2.addWidget(self.phone)
        self.textphone = QtWidgets.QTextEdit(self.horizontalLayoutWidget_5)
        self.textphone.setObjectName("textphone")
        self.phone_2.addWidget(self.textphone)
        self.horizontalLayoutWidget_6 = QWidget(self)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(0, 240, 841, 31))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.site_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.site_2.setContentsMargins(11, 0, 1, 0)
        self.site_2.setSpacing(8)
        self.site_2.setObjectName("site_2")
        self.site = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.site.setObjectName("site")
        self.site_2.addWidget(self.site)
        self.textsite = QtWidgets.QTextEdit(self.horizontalLayoutWidget_6)
        self.textsite.setObjectName("textsite")
        self.site_2.addWidget(self.textsite)
        self.horizontalLayoutWidget_7 = QWidget(self)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(0, 280, 841, 31))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.email_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.email_2.setContentsMargins(11, 0, 1, 0)
        self.email_2.setSpacing(8)
        self.email_2.setObjectName("email_2")
        self.email = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        self.email.setObjectName("email")
        self.email_2.addWidget(self.email)
        self.textemail = QtWidgets.QTextEdit(self.horizontalLayoutWidget_7)
        self.textemail.setObjectName("textemail")
        self.email_2.addWidget(self.textemail)
        self.horizontalLayoutWidget_8 = QWidget(self)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(0, 330, 841, 31))
        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_8")
        self.inn_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.inn_2.setContentsMargins(11, 0, 1, 0)
        self.inn_2.setSpacing(8)
        self.inn_2.setObjectName("inn_2")
        self.inn = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        self.inn.setObjectName("inn")
        self.inn_2.addWidget(self.inn)
        self.textinn = QtWidgets.QTextEdit(self.horizontalLayoutWidget_8)
        self.textinn.setObjectName("textinn")
        self.inn_2.addWidget(self.textinn)
        self.horizontalLayoutWidget_9 = QWidget(self)
        self.horizontalLayoutWidget_9.setGeometry(QtCore.QRect(0, 380, 841, 31))
        self.horizontalLayoutWidget_9.setObjectName("horizontalLayoutWidget_9")
        self.kpp_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_9)
        self.kpp_2.setContentsMargins(11, 0, 1, 0)
        self.kpp_2.setSpacing(8)
        self.kpp_2.setObjectName("kpp_2")
        self.kpp = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        self.kpp.setObjectName("kpp")
        self.kpp_2.addWidget(self.kpp)
        self.textkpp = QtWidgets.QTextEdit(self.horizontalLayoutWidget_9)
        self.textkpp.setObjectName("textkpp")
        self.kpp_2.addWidget(self.textkpp)
        self.horizontalLayoutWidget_10 = QWidget(self)
        self.horizontalLayoutWidget_10.setGeometry(QtCore.QRect(0, 430, 841, 31))
        self.horizontalLayoutWidget_10.setObjectName("horizontalLayoutWidget_10")
        self.okpo_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_10)
        self.okpo_2.setContentsMargins(11, 0, 1, 0)
        self.okpo_2.setSpacing(8)
        self.okpo_2.setObjectName("okpo_2")
        self.okpo = QtWidgets.QLabel(self.horizontalLayoutWidget_10)
        self.okpo.setObjectName("okpo")
        self.okpo_2.addWidget(self.okpo)
        self.textokpo = QtWidgets.QTextEdit(self.horizontalLayoutWidget_10)
        self.textokpo.setObjectName("textokpo")
        self.okpo_2.addWidget(self.textokpo)
        self.horizontalLayoutWidget_11 = QWidget(self)
        self.horizontalLayoutWidget_11.setGeometry(QtCore.QRect(0, 480, 841, 31))
        self.horizontalLayoutWidget_11.setObjectName("horizontalLayoutWidget_11")
        self.ogrn_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_11)
        self.ogrn_2.setContentsMargins(11, 0, 1, 0)
        self.ogrn_2.setSpacing(8)
        self.ogrn_2.setObjectName("ogrn_2")
        self.ogrn = QtWidgets.QLabel(self.horizontalLayoutWidget_11)
        self.ogrn.setObjectName("ogrn")
        self.ogrn_2.addWidget(self.ogrn)
        self.textogrn = QtWidgets.QTextEdit(self.horizontalLayoutWidget_11)
        self.textogrn.setObjectName("textogrn")
        self.ogrn_2.addWidget(self.textogrn)
        self.horizontalLayoutWidget_12 = QWidget(self)
        self.horizontalLayoutWidget_12.setGeometry(QtCore.QRect(0, 520, 841, 31))
        self.horizontalLayoutWidget_12.setObjectName("horizontalLayoutWidget_12")
        self.in__Reg_stad_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_12)
        self.in__Reg_stad_2.setContentsMargins(11, 0, 1, 0)
        self.in__Reg_stad_2.setSpacing(8)
        self.in__Reg_stad_2.setObjectName("in__Reg_stad_2")
        self.in__Reg_stad = QtWidgets.QLabel(self.horizontalLayoutWidget_12)
        self.in__Reg_stad.setAutoFillBackground(False)
        self.in__Reg_stad.setStyleSheet("background-color: rgb(255, 0, 255);")
        self.in__Reg_stad.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.in__Reg_stad.setFrameShadow(QtWidgets.QFrame.Plain)
        self.in__Reg_stad.setLineWidth(1)
        self.in__Reg_stad.setWordWrap(False)
        self.in__Reg_stad.setObjectName("in__Reg_stad")
        self.in__Reg_stad_2.addWidget(self.in__Reg_stad)
        self.textin__Reg_stad = QtWidgets.QTextEdit(self.horizontalLayoutWidget_12)
        # self.textin__Reg_stad.setFocusPolicy(QtCore.Qt.NoFocus)
        self.textin__Reg_stad.setObjectName("textin__Reg_stad")
        self.in__Reg_stad_2.addWidget(self.textin__Reg_stad)
        self.horizontalLayoutWidget_13 = QWidget(self)
        self.horizontalLayoutWidget_13.setGeometry(QtCore.QRect(0, 570, 841, 31))
        self.horizontalLayoutWidget_13.setObjectName("horizontalLayoutWidget_13")
        self.conf_in_expluatation_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_13)
        self.conf_in_expluatation_2.setContentsMargins(11, 0, 1, 0)
        self.conf_in_expluatation_2.setSpacing(8)
        self.conf_in_expluatation_2.setObjectName("conf_in_expluatation_2")
        self.conf_in_expluatation = QtWidgets.QLabel(self.horizontalLayoutWidget_13)
        self.conf_in_expluatation.setStyleSheet("background-color: rgb(255, 0, 255);")
        self.conf_in_expluatation.setObjectName("conf_in_expluatation")
        self.conf_in_expluatation_2.addWidget(self.conf_in_expluatation)
        self.textconf_in_expluatation = QtWidgets.QTextEdit(self.horizontalLayoutWidget_13)
        self.textconf_in_expluatation.setObjectName("textconf_in_expluatation")
        self.conf_in_expluatation_2.addWidget(self.textconf_in_expluatation)
        self.horizontalLayoutWidget_14 = QWidget(self)
        self.horizontalLayoutWidget_14.setGeometry(QtCore.QRect(0, 620, 841, 31))
        self.horizontalLayoutWidget_14.setObjectName("horizontalLayoutWidget_14")
        self.instr_pub_order_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_14)
        self.instr_pub_order_2.setContentsMargins(11, 0, 1, 0)
        self.instr_pub_order_2.setSpacing(8)
        self.instr_pub_order_2.setObjectName("instr_pub_order_2")
        self.instr_pub_order = QtWidgets.QLabel(self.horizontalLayoutWidget_14)
        self.instr_pub_order.setStyleSheet("background-color: rgb(255, 0, 255);")
        self.instr_pub_order.setObjectName("instr_pub_order")
        self.instr_pub_order_2.addWidget(self.instr_pub_order)
        self.textinstr_pub_order = QtWidgets.QTextEdit(self.horizontalLayoutWidget_14)
        self.textinstr_pub_order.setObjectName("textinstr_pub_order")
        self.instr_pub_order_2.addWidget(self.textinstr_pub_order)
        self.horizontalLayoutWidget_15 = QWidget(self)
        self.horizontalLayoutWidget_15.setGeometry(QtCore.QRect(0, 670, 841, 31))
        self.horizontalLayoutWidget_15.setObjectName("horizontalLayoutWidget_15")
        self.instr_pub_order_date_until_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_15)
        self.instr_pub_order_date_until_2.setContentsMargins(11, 0, 1, 0)
        self.instr_pub_order_date_until_2.setSpacing(8)
        self.instr_pub_order_date_until_2.setObjectName("instr_pub_order_date_until_2")
        self.instr_pub_order_date_until = QtWidgets.QLabel(self.horizontalLayoutWidget_15)
        self.instr_pub_order_date_until.setObjectName("instr_pub_order_date_until")
        self.instr_pub_order_date_until_2.addWidget(self.instr_pub_order_date_until)
        self.textinstr_pub_order_date_until = QtWidgets.QTextEdit(self.horizontalLayoutWidget_15)
        self.textinstr_pub_order_date_until.setObjectName("textinstr_pub_order_date_until")
        self.instr_pub_order_date_until_2.addWidget(self.textinstr_pub_order_date_until)
        self.horizontalLayoutWidget_16 = QWidget(self)
        self.horizontalLayoutWidget_16.setGeometry(QtCore.QRect(0, 720, 841, 31))
        self.horizontalLayoutWidget_16.setObjectName("horizontalLayoutWidget_16")
        self.act_categ_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_16)
        self.act_categ_2.setContentsMargins(11, 0, 1, 0)
        self.act_categ_2.setSpacing(8)
        self.act_categ_2.setObjectName("act_categ_2")
        self.act_categ = QtWidgets.QLabel(self.horizontalLayoutWidget_16)
        self.act_categ.setStyleSheet("background-color: rgb(255, 0, 255);")
        self.act_categ.setObjectName("act_categ")
        self.act_categ_2.addWidget(self.act_categ)
        self.textact_categ = QtWidgets.QTextEdit(self.horizontalLayoutWidget_16)
        self.textact_categ.setObjectName("textact_categ")
        self.act_categ_2.addWidget(self.textact_categ)
        self.horizontalLayoutWidget_17 = QWidget(self)
        self.horizontalLayoutWidget_17.setGeometry(QtCore.QRect(0, 770, 841, 31))
        self.horizontalLayoutWidget_17.setObjectName("horizontalLayoutWidget_17")
        self.act_categ_date_until_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_17)
        self.act_categ_date_until_2.setContentsMargins(11, 0, 1, 0)
        self.act_categ_date_until_2.setSpacing(8)
        self.act_categ_date_until_2.setObjectName("act_categ_date_until_2")
        self.act_categ_date_until = QtWidgets.QLabel(self.horizontalLayoutWidget_17)
        self.act_categ_date_until.setObjectName("act_categ_date_until")
        self.act_categ_date_until_2.addWidget(self.act_categ_date_until)
        self.textact_categ_date_until = QtWidgets.QTextEdit(self.horizontalLayoutWidget_17)
        self.textact_categ_date_until.setObjectName("textact_categ_date_until")
        self.act_categ_date_until_2.addWidget(self.textact_categ_date_until)
        self.horizontalLayoutWidget_18 = QWidget(self)
        self.horizontalLayoutWidget_18.setGeometry(QtCore.QRect(0, 820, 841, 31))
        self.horizontalLayoutWidget_18.setObjectName("horizontalLayoutWidget_18")
        self.statd_plan_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_18)
        self.statd_plan_2.setContentsMargins(11, 0, 1, 0)
        self.statd_plan_2.setSpacing(8)
        self.statd_plan_2.setObjectName("statd_plan_2")
        self.statd_plan = QtWidgets.QLabel(self.horizontalLayoutWidget_18)
        self.statd_plan.setStyleSheet("background-color: rgb(255, 0, 255);")
        self.statd_plan.setObjectName("statd_plan")
        self.statd_plan_2.addWidget(self.statd_plan)
        self.textstatd_plan = QtWidgets.QTextEdit(self.horizontalLayoutWidget_18)
        self.textstatd_plan.setObjectName("textstatd_plan")
        self.statd_plan_2.addWidget(self.textstatd_plan)
        self.creat_stadium_button = QCommandLinkButton(self)
        self.creat_stadium_button.setGeometry(QtCore.QRect(660, 860, 185, 41))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(16)
        self.creat_stadium_button.setFont(font)
        self.creat_stadium_button.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.creat_stadium_button.setObjectName("creat_stadium_button")
        self.creat_stadium_button.clicked.connect(self.creat_stadium)

        self.retranslateUi(QWidget)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self, QWidget):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Creat_Stadium", "Form"))
        self.name.setText(_translate("Creat_Stadium", "Название Стадиона"))
        self.shrt_name.setText(_translate("Creat_Stadium", "Сокращенное название"))
        self.o_p_f.setText(_translate("Creat_Stadium", "Организацонное-правовая форма"))
        self.jur_addr.setText(_translate("Creat_Stadium", "Адрес"))
        self.phone.setText(_translate("Creat_Stadium", "Телефон"))
        self.site.setText(_translate("Creat_Stadium", "Сайт"))
        self.email.setText(_translate("Creat_Stadium", "email"))
        self.inn.setText(_translate("Creat_Stadium", "ИНН"))
        self.kpp.setText(_translate("Creat_Stadium", "КПП"))
        self.okpo.setText(_translate("Creat_Stadium", "ОКПО"))
        self.ogrn.setText(_translate("Creat_Stadium", "ОГРН"))
        self.in__Reg_stad.setText(_translate("Creat_Stadium", "В Реестре Объектов Спорта"))
        self.conf_in_expluatation.setText(_translate("Creat_Stadium", "Ввод в эксплуатацию"))
        self.instr_pub_order.setText(_translate("Creat_Stadium", "Инструкция по безопасности"))
        self.instr_pub_order_date_until.setText(_translate("Creat_Stadium", "Дата окончания Инструкции"))
        self.act_categ.setText(_translate("Creat_Stadium", "Акт категорирования"))
        self.act_categ_date_until.setText(_translate("Creat_Stadium", "Дата окончания акта"))
        self.statd_plan.setText(_translate("Creat_Stadium", "План Стадиона"))
        self.creat_stadium_button.setText(_translate("Creat_Stadium", "Создать"))

    def creat_stadium(self):
        name=self.textname.toPlainText()
        shrt_name=self.textshrt_name.toPlainText()
        o_p_f=self.texto_p_f.toPlainText()
        jur_addr=self.textjur_addr.toPlainText()
        phone=self.textphone.toPlainText()
        site=self.textsite.toPlainText()
        email=self.textemail.toPlainText()
        inn=self.textinn.toPlainText()
        kpp=self.textkpp.toPlainText()
        okpo=self.textokpo.toPlainText()
        ogrn=self.textogrn.toPlainText()
        in__Reg_stad=self.textin__Reg_stad.toPlainText()
        conf_in_expluatation=self.textconf_in_expluatation.toPlainText()
        instr_pub_order=self.textinstr_pub_order.toPlainText()
        instr_pub_order_date_until=self.textinstr_pub_order_date_until.toPlainText()
        act_categ=self.textact_categ.toPlainText()
        act_categ_date_until=self.textact_categ_date_until.toPlainText()
        statd_plan=self.textstatd_plan.toPlainText()
        print(name,shrt_name,o_p_f,jur_addr,phone,site,email,inn,kpp,okpo,ogrn,in__Reg_stad,
              conf_in_expluatation,instr_pub_order,instr_pub_order_date_until,act_categ,
              act_categ_date_until,statd_plan)
        stad=Stadium(name,shrt_name,o_p_f,jur_addr,phone,site,email,inn,kpp,okpo,ogrn,in__Reg_stad,
                      conf_in_expluatation,instr_pub_order,instr_pub_order_date_until,act_categ,
                      act_categ_date_until,statd_plan)
        stad.add_to_db()
        print('Стадион создан')


class MainWindow(QMainWindow):
    def __init__(self):
        super(MainWindow, self).__init__()
        self.setObjectName("MainWindow")
        self.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("Gabriola")
        font.setPointSize(16)
        self.setFont(font)
        self.centralwidget = QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.creat_stadium_button = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.creat_stadium_button.setGeometry(QtCore.QRect(10, 20, 201, 41))
        self.creat_stadium_button.setObjectName("creat_stadium_button")
        self.creat_club_button = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.creat_club_button.setGeometry(QtCore.QRect(10, 80, 201, 41))
        self.creat_club_button.setObjectName("creat_club_button")
        self.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 45))
        self.menubar.setObjectName("menubar")
        self.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)
        self.creat_stadium_button.clicked.connect(self.creat_stadium)
        self.creat_club_button.clicked.connect(self.creat_club)
        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.creat_stadium_button.setText(_translate("MainWindow", "Создать Стадион"))
        self.creat_club_button.setText(_translate("MainWindow", "Создать Клуб"))

    def creat_stadium(self):
        self.w1 = WindowStadium()
        self.w1.show()

    def creat_club(self):
        self.w2 = WindowClub()
        self.w2.show()

if __name__ == '__main__':
    app = QApplication(sys.argv)
    w = MainWindow()
    w.show()
    sys.exit(app.exec_())